### ISSUE TITLE
Testing Assertions

### ISSUE THREAD

**Issue by jcsoriano** [mpbarlow/laravel-queue-debouncer#10]
Hello, thanks for this great package! Just wanted to ask how you recommend testing this, i.e. how do you think is the best way to assert that the job has been debounced :)

**Comment by mpbarlow** [comment]
Hi, thanks for the kind words 😀

It's admittedly a very difficult thing to test with the tooling available, due to the asynchronous nature of what the package does. A good place to start would be the package's own tests, particularly [DebounceTest](https://github.com/mpbarlow/laravel-queue-debouncer/blob/master/tests/DebounceTest.php). 

I'm not sure if following that example will be 100% appropriate for your requirements, but hopefully it will serve as a good starting point at least.
